# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.TextField(max_length=10)),
                ('gbp_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=255)),
                ('transaction_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_brand', models.CharField(max_length=255)),
                ('card_issuer', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('card_country', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
