# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20160925_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.TextField(default='GBP', max_length=10),
            preserve_default=False,
        ),
    ]
