# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processor',
            name='base_rate',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processor',
            name='percentage_rate',
            field=models.FloatField(default=0.2),
            preserve_default=False,
        ),
    ]
